apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: application-locmns
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
  type: ClusterIP