apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: application-locmns
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: backend
