version: '2.4'

services:
  backend:
    image: backendlocmns:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=dobelocmns
      - DB_PORT=3306
    depends_on:
      - dobelocmns
    networks:
      - backend-network

  dobelocmns:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend-network
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: dobelocmns
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  db-data:
