version: '3.8'

services:
  backend:
    image: backendlocmns:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=dobelocmns
      - DB_PORT=3306
    depends_on:
      - dobelocmns
    networks:
      - backend-network

  dobelocmns:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  backend-network:

volumes:
  db-data:

