apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: application-locmns
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mysql"
