apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql/mysql-deployment.yml
  - backend/app-back-deployment.yml
  - php/myadmin-deployment.yml
  - mysql/msql-clusterIP-mysql.yml
  - backend/app-nodeport.yml
  - php/myadmin-clusterIP.yml
  - mysql/mysql-pvc.yml
  - backend/app-namespace.yml
  - backend/app-secret.yml
  - frontend/app-back-deployment.yml
  - frontend/app-nodeport.yml
